import {
  PURCHASE_PLAN_GROUP_PERMISSION,
  PURCHASE_PLAN_PERMISSION,
} from './purchase-plan';
import {
  PURCHASE_REQUEST_GROUP_PERMISSION,
  PURCHASE_REQUEST_PERMISSION,
} from './purchase-request';

export const PERMISSION = [
  ...PURCHASE_PLAN_PERMISSION,
  ...PURCHASE_REQUEST_PERMISSION,
];

export const GROUP_PERMISSION = [
  PURCHASE_PLAN_GROUP_PERMISSION,
  PURCHASE_REQUEST_GROUP_PERMISSION,
];

export const INSERT_PERMISSION = {
  permission: PERMISSION,
  groupPermission: GROUP_PERMISSION,
};
