name: Deploy User Service to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e # BẮT BUỘC: Dừng ngay lập tức nếu có bất kỳ lệnh nào bị lỗi

            mkdir -p ~/projects/user-service
            cd ~/projects/user-service

            # Kéo code mới nhất từ nhánh main (Dành cho Repo Public)
            if [ ! -d ".git" ]; then
              git clone https://github.com/khanh-ptit/user-service.git .
            else
              git fetch --all
              git reset --hard origin/main
              git pull origin main
            fi

            # Build Docker image
            docker build -t user-service:latest .

            # Dừng và xoá container cũ (nếu có)
            docker stop user-service || true
            docker rm user-service || true

            # Chạy container mới với biến môi trường và mạng chung (mesx-net)
            docker run -d --name user-service --env-file .env --network mesx-net -p 3000:3000 user-service:latest

            # Xóa các image cũ lủng lẳng để giải phóng bộ nhớ
            docker image prune -f
